<?php

$meshrider_hotels = [
 
    1 => [
        'id' => 1,
        'region' => 'amman',
        'name' => 'فندق عمّان رويال',
        'stars' => 5,
        'image' => 'https://cdn.prod.website-files.com/6087d683edfb0155b650657d/686d06bc888cb8150259e6c1_Amman-main-V2.jpg',
        'price' => '150 دينار',
        'location' => 'الدوار الخامس، عمّان',
        'short_desc' => 'فندق فاخر بإطلالات بانورامية على مدينة عمّان.',
        'desc' => 'يعتبر فندق عمّان رويال من أفخم الفنادق في العاصمة، حيث يتميز بتصميم عصري وإطلالات بانورامية على مدينة عمّان. يوفر الفندق تجربة استثنائية للضيوف من خلال خدمات عالية الجودة ومطاعم عالمية.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-parking', 'name' => 'موقف سيارات'],
            ['icon' => 'fa-swimming-pool', 'name' => 'مسبح خارجي'],
            ['icon' => 'fa-utensils', 'name' => 'مطعم فاخر'],
            ['icon' => 'fa-dumbbell', 'name' => 'نادي رياضي'],
            ['icon' => 'fa-spa', 'name' => 'مركز سبا']
        ],
        'phone' => '+962 6 111 2222',
        'whatsapp' => '962791112222',
        'status' => 'متاح للحجز',
    ],
    2 => [
        'id' => 2,
        'region' => 'amman',
        'name' => 'أجنحة بوليفارد',
        'stars' => 4,
        'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        'price' => '90 دينار',
        'location' => 'العبدلي، عمّان',
        'short_desc' => 'شقق فندقية عصرية في قلب العبدلي.',
        'desc' => 'يوفر بوليفارد أجنحة فندقية مجهزة بالكامل ومثالية للعائلات ورجال الأعمال. يقع بالقرب من منطقة التسوق والأعمال الرئيسية في العبدلي.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-parking', 'name' => 'موقف سيارات'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف مركزي'],
            ['icon' => 'fa-coffee', 'name' => 'إفطار مجاني'],
        ],
        'phone' => '+962 6 333 4444',
        'whatsapp' => '962793334444',
        'status' => 'متاح للحجز',
    ],
    3 => [
        'id' => 3,
        'region' => 'amman',
        'name' => 'فندق عمّان كلاسيك',
        'stars' => 3,
        'image' => ' https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=90',
        'price' => '45 دينار',
        'location' => 'وسط البلد، عمّان',
        'short_desc' => 'إقامة اقتصادية ومريحة بالقرب من المدرج الروماني.',
        'desc' => 'فندق اقتصادي ممتاز يقع في قلب وسط البلد، على بعد دقائق مشياً من المدرج الروماني وجبل القلعة. خيار مثالي للمسافرين الباحثين عن استكشاف الثقافة المحلية.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف'],
            ['icon' => 'fa-coffee', 'name' => 'إفطار بسيط'],
        ],
        'phone' => '+962 6 555 6666',
        'whatsapp' => '962795556666',
        'status' => 'متاح للحجز',
    ],
    4 => [
        'id' => 4,
        'region' => 'amman',
        'name' => 'فندق البتراء الصغير',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80',
        'price' => '40 دينار',
        'location' => 'الدوار الثاني، عمّان',
        'short_desc' => 'فندق بوتيك هادئ ونظيف بإدارة عائلية.',
        'desc' => 'يتميز هذا الفندق ذو الثلاث نجوم بغرف نظيفة ومريحة وطاقم عمل ودود. يقع في منطقة هادئة قريبة من شارع الرينبو.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف'],
        ],
        'phone' => '+962 6 777 8888',
        'whatsapp' => '962797778888',
        'status' => 'متاح للحجز',
    ],
    5 => [
        'id' => 5,
        'region' => 'amman',
        'name' => 'فندق جبل القلعة',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&w=800&q=80',
        'price' => '35 دينار',
        'location' => 'جبل الحسين، عمّان',
        'short_desc' => 'إطلالات رائعة على المدينة بأسعار مناسبة للجميع.',
        'desc' => 'خيار مفضل للشباب والمجموعات، يوفر غرفاً مريحة وتراساً بإطلالة ساحرة على جبل القلعة.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-parking', 'name' => 'مواقف عامة'],
            ['icon' => 'fa-coffee', 'name' => 'مقهى بالتراس'],
        ],
        'phone' => '+962 6 999 0000',
        'whatsapp' => '962799990000',
        'status' => 'متاح للحجز',
    ],


    6 => [
        'id' => 6,
        'region' => 'aqaba',
        'name' => 'منتجع البحر الأحمر',
        'stars' => 5,
        'image' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        'price' => '200 دينار',
        'location' => 'شاطئ العقبة الجنوبي',
        'short_desc' => 'منتجع فاخر على شاطئ البحر يضم مسابح خاصة.',
        'desc' => 'تمتع بإقامة ملوكية في منتجع البحر الأحمر، مع شاطئ خاص، مسابح لامتناهية، ومراكز غوص عالمية.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-swimming-pool', 'name' => 'مسبح خاص'],
            ['icon' => 'fa-umbrella-beach', 'name' => 'شاطئ خاص'],
            ['icon' => 'fa-utensils', 'name' => 'مطاعم بحرية'],
            ['icon' => 'fa-water', 'name' => 'مركز غوص']
        ],
        'phone' => '+962 3 111 2222',
        'whatsapp' => '962791112222',
        'status' => 'متاح للحجز',
    ],
    7 => [
        'id' => 7,
        'region' => 'aqaba',
        'name' => 'فندق المرجان',
        'stars' => 4,
        'image' => 'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?auto=format&fit=crop&w=800&q=80',
        'price' => '110 دينار',
        'location' => 'وسط مدينة العقبة',
        'short_desc' => 'فندق عصري في قلب السوق وقريب من البحر.',
        'desc' => 'يتميز بموقعه الاستراتيجي في وسط المدينة، مما يجعله مثالياً للتسوق والاستمتاع بالمطاعم المحلية، مع سهولة الوصول إلى الشاطئ.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف مركزي'],
            ['icon' => 'fa-swimming-pool', 'name' => 'مسبح خارجي'],
        ],
        'phone' => '+962 3 333 4444',
        'whatsapp' => '962793334444',
        'status' => 'متاح للحجز',
    ],
    8 => [
        'id' => 8,
        'region' => 'aqaba',
        'name' => 'فندق الشراع',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
        'price' => '55 دينار',
        'location' => 'المنطقة الفندقية الثانية',
        'short_desc' => 'إقامة مريحة وبأسعار معقولة للعائلات.',
        'desc' => 'يقدم الفندق غرفاً نظيفة ومريحة مع مسبح صغير وإفطار مجاني. خيار ممتاز لمن يبحث عن التوفير في العقبة.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف'],
            ['icon' => 'fa-coffee', 'name' => 'إفطار مجاني'],
        ],
        'phone' => '+962 3 555 6666',
        'whatsapp' => '962795556666',
        'status' => 'متاح للحجز',
    ],
    9 => [
        'id' => 9,
        'region' => 'aqaba',
        'name' => 'نزل الصيادين',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
        'price' => '45 دينار',
        'location' => 'قرب ميناء الصيد القديم',
        'short_desc' => 'نزل بسيط ومريح يفضله الغواصون.',
        'desc' => 'إذا كنت من عشاق الغوص، فهذا النزل الاقتصادي يوفر لك إقامة عملية قريبة من مراكز الغوص بتكلفة بسيطة جداً.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف'],
        ],
        'phone' => '+962 3 777 8888',
        'whatsapp' => '962797778888',
        'status' => 'متاح للحجز',
    ],

   
    10 => [
        'id' => 10,
        'region' => 'wadirum',
        'name' => 'مخيم الفقاعات الفاخر',
        'stars' => 5,
        'image' => ' https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=90',
        'price' => '220 دينار',
        'location' => 'محمية وادي رم',
        'short_desc' => 'تجربة خيالية للنوم تحت النجوم في خيام زجاجية.',
        'desc' => 'يوفر هذا المخيم تجربة غير مسبوقة حيث يمكنك مشاهدة السماء المرصعة بالنجوم من داخل غرفتك الفقاعية المكيفة والفاخرة بالكامل.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف مركزي'],
            ['icon' => 'fa-star', 'name' => 'سقف زجاجي للنجوم'],
            ['icon' => 'fa-utensils', 'name' => 'عشاء زرب تقليدي'],
            ['icon' => 'fa-car', 'name' => 'جولات سفاري']
        ],
        'phone' => '+962 79 111 2222',
        'whatsapp' => '962791112222',
        'status' => 'متاح للحجز',
    ],
    11 => [
        'id' => 11,
        'region' => 'wadirum',
        'name' => 'مخيم البدو الأصيل',
        'stars' => 4,
        'image' => 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=80',
        'price' => '85 دينار',
        'location' => 'وسط وادي رم',
        'short_desc' => 'خيام بدوية مطورة تجمع بين الأصالة والراحة.',
        'desc' => 'استمتع بالضيافة البدوية الأصيلة مع خيام مطورة تحتوي على حمامات خاصة وأسرة مريحة، بالإضافة إلى جلسات مسائية حول النار.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'إنترنت محدود'],
            ['icon' => 'fa-fire', 'name' => 'جلسات مسائية'],
            ['icon' => 'fa-coffee', 'name' => 'إفطار مجاني'],
        ],
        'phone' => '+962 79 333 4444',
        'whatsapp' => '962793334444',
        'status' => 'متاح للحجز',
    ],
    12 => [
        'id' => 12,
        'region' => 'wadirum',
        'name' => 'مخيم القمر الصحراوي',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=800&q=80',
        'price' => '35 دينار',
        'location' => 'القرية البدوية',
        'short_desc' => 'تجربة اقتصادية ودافئة للرحالة والشباب.',
        'desc' => 'مخيم تقليدي يوفر خياماً نظيفة وحمامات مشتركة. مثالي للمسافرين بميزانية محدودة الذين يبحثون عن الأجواء البدوية الحقيقية.',
        'amenities' => [
            ['icon' => 'fa-campground', 'name' => 'خيام تقليدية'],
            ['icon' => 'fa-fire', 'name' => 'نار المخيم'],
        ],
        'phone' => '+962 79 555 6666',
        'whatsapp' => '962795556666',
        'status' => 'متاح للحجز',
    ],
    13 => [
        'id' => 13,
        'region' => 'wadirum',
        'name' => 'مخيم النجوم',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=90',
        'price' => '40 دينار',
        'location' => 'المنطقة المحمية',
        'short_desc' => 'إقامة بسيطة ونظيفة مع وجبات لذيذة.',
        'desc' => 'يقدم هذا المخيم قيمة رائعة مقابل المال مع خيام مرتبة ومرافق نظيفة، ويشتهر بتقديم وجبة الزرب اللذيذة.',
        'amenities' => [
            ['icon' => 'fa-campground', 'name' => 'خيام مشتركة وخاصة'],
            ['icon' => 'fa-coffee', 'name' => 'إفطار مشمول'],
        ],
        'phone' => '+962 79 777 8888',
        'whatsapp' => '962797778888',
        'status' => 'متاح للحجز',
    ],

   
    14 => [
        'id' => 14,
        'region' => 'jerash',
        'name' => 'فندق غصن الزيتون',
        'stars' => 4,
        'image' => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=80',
        'price' => '75 دينار',
        'location' => 'محمية دبين / جرش',
        'short_desc' => 'منتجع بيئي هادئ بين أشجار الزيتون والصنوبر.',
        'desc' => 'يوفر فندق غصن الزيتون تجربة بيئية رائعة في أحضان الطبيعة، مع مسبح خارجي وإطلالات خضراء مريحة للنفس، قريباً من آثار جرش.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-swimming-pool', 'name' => 'مسبح خارجي'],
            ['icon' => 'fa-leaf', 'name' => 'بيئة خضراء'],
            ['icon' => 'fa-parking', 'name' => 'مواقف مجانية'],
        ],
        'phone' => '+962 2 111 2222',
        'whatsapp' => '962791112222',
        'status' => 'متاح للحجز',
    ],
    15 => [
        'id' => 15,
        'region' => 'jerash',
        'name' => 'فندق جرش الأثري',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1560662105-57f8ad6ae2d1?auto=format&fit=crop&w=800&q=80',
        'price' => '45 دينار',
        'location' => 'بجوار البوابة الجنوبية',
        'short_desc' => 'موقع استراتيجي على بعد خطوات من الآثار الرومانية.',
        'desc' => 'فندق 3 نجوم نظيف وعملي يوفر راحة البال للقادمين لاستكشاف الآثار، يتميز بقربه الشديد من البوابة الرئيسية لمدينة جرش الأثرية.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف'],
            ['icon' => 'fa-coffee', 'name' => 'إفطار مشمول'],
        ],
        'phone' => '+962 2 333 4444',
        'whatsapp' => '962793334444',
        'status' => 'متاح للحجز',
    ],
    16 => [
        'id' => 16,
        'region' => 'jerash',
        'name' => 'شقق الرومان الفندقية',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
        'price' => '50 دينار',
        'location' => 'وسط مدينة جرش',
        'short_desc' => 'شقق واسعة تناسب العائلات الكبيرة الميزانية.',
        'desc' => 'يوفر هذا المكان شققاً فندقية بغرفتي نوم وصالة لتناسب العائلات الزائرة لجرش، ويتميز بالنظافة والخدمة الجيدة بسعر مناسب.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-parking', 'name' => 'موقف سيارات'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف'],
        ],
        'phone' => '+962 2 555 6666',
        'whatsapp' => '962795556666',
        'status' => 'متاح للحجز',
    ],
    17 => [
        'id' => 17,
        'region' => 'jerash',
        'name' => 'فندق أرتيميس',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
        'price' => '40 دينار',
        'location' => 'شارع الجبل',
        'short_desc' => 'فندق صغير ومريح مع إطلالة على الآثار.',
        'desc' => 'فندق مريح وصغير بإطلالة خلابة من السطح على الأعمدة الرومانية، يوفر غرفاً بسيطة ونظيفة وأجواء دافئة.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-eye', 'name' => 'تراس بانورامي'],
        ],
        'phone' => '+962 2 777 8888',
        'whatsapp' => '962797778888',
        'status' => 'متاح للحجز',
    ],

  
    18 => [
        'id' => 18,
        'region' => 'irbid',
        'name' => 'فندق سفن روزز إربد',
        'stars' => 4,
        'image' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80',
        'price' => '85 دينار',
        'location' => 'شارع الجامعة',
        'short_desc' => 'أفضل الفنادق العصرية في عروس الشمال.',
        'desc' => 'يوفر فندق سفن روزز إقامة فاخرة وعصرية مع مطعم ممتاز وقربه من جامعة اليرموك والمناطق الحيوية في إربد.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-parking', 'name' => 'موقف سيارات'],
            ['icon' => 'fa-dumbbell', 'name' => 'نادي رياضي'],
            ['icon' => 'fa-utensils', 'name' => 'مطعم'],
        ],
        'phone' => '+962 2 111 2222',
        'whatsapp' => '962791112222',
        'status' => 'متاح للحجز',
    ],
    19 => [
        'id' => 19,
        'region' => 'irbid',
        'name' => 'أجنحة عروس الشمال',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
        'price' => '45 دينار',
        'location' => 'دوار النسيم',
        'short_desc' => 'أجنحة فندقية نظيفة ومريحة بأسعار منافسة.',
        'desc' => 'خيار ممتاز للعائلات ورجال الأعمال، يقدم أجنحة متكاملة بخدمات تنظيف يومية وإنترنت سريع بأسعار في متناول الجميع.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف'],
            ['icon' => 'fa-coffee', 'name' => 'إفطار مجاني'],
        ],
        'phone' => '+962 2 333 4444',
        'whatsapp' => '962793334444',
        'status' => 'متاح للحجز',
    ],
    20 => [
        'id' => 20,
        'region' => 'irbid',
        'name' => 'فندق إربد بلازا',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=800&q=80',
        'price' => '40 دينار',
        'location' => 'وسط السوق',
        'short_desc' => 'إقامة اقتصادية في قلب الحركة التجارية.',
        'desc' => 'يتميز بموقعه الحيوي في وسط إربد لتسهيل الوصول للأسواق والمطاعم الشعبية. الغرف نظيفة وواسعة تناسب الميزانيات المحدودة.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-snowflake', 'name' => 'تكييف'],
        ],
        'phone' => '+962 2 555 6666',
        'whatsapp' => '962795556666',
        'status' => 'متاح للحجز',
    ],
    21 => [
        'id' => 21,
        'region' => 'irbid',
        'name' => 'شقق جود',
        'stars' => 3,
        'image' => 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        'price' => '35 دينار',
        'location' => 'شارع بغداد',
        'short_desc' => 'شقق مفروشة هادئة للإقامات القصيرة والطويلة.',
        'desc' => 'شقق بسيطة ومرتبة تناسب الطلاب والعائلات الصغيرة التي تبحث عن خيار اقتصادي وعملي في إربد.',
        'amenities' => [
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-kitchen-set', 'name' => 'مطبخ صغير'],
            ['icon' => 'fa-parking', 'name' => 'موقف سيارات'],
        ],
        'phone' => '+962 2 777 8888',
        'whatsapp' => '962797778888',
        'status' => 'متاح للحجز',
    ],

  
    22 => [
        'id' => 22,
        'region' => 'deadsea',
        'name' => 'منتجع وسبا كمبينسكي عشتار',
        'stars' => 5,
        'image' => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80',
        'price' => '250 دينار',
        'location' => 'طريق البحر الميت، سويمة',
        'short_desc' => 'منتجع فاخر يوفر أكبر سبا في الشرق الأوسط وإطلالات ساحرة.',
        'desc' => 'يتميز منتجع كمبينسكي عشتار البحر الميت بتصميمه المستوحى من حدائق بابل المعلقة. يوفر شواطئ خاصة، أحواض سباحة إنفينيتي، وأكبر مركز سبا وعلاج بطينة البحر الميت في المنطقة.',
        'amenities' => [
            ['icon' => 'fa-spa', 'name' => 'علاج بطينة البحر الميت'],
            ['icon' => 'fa-swimming-pool', 'name' => '9 مسابح خارجية'],
            ['icon' => 'fa-umbrella-beach', 'name' => 'شاطئ خاص'],
            ['icon' => 'fa-wifi', 'name' => 'واي فاي مجاني'],
            ['icon' => 'fa-utensils', 'name' => 'مطاعم عالمية']
        ],
        'phone' => '+962 5 356 8888',
        'whatsapp' => '962791234567',
        'status' => 'متاح للحجز',
    ],
    23 => [
        'id' => 23,
        'region' => 'deadsea',
        'name' => 'ماريوت منتجع وسبا البحر الميت',
        'stars' => 5,
        'image' => 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=80',
        'price' => '190 دينار',
        'location' => 'البحر الميت، سويمة',
        'short_desc' => 'وجهة استجمام متكاملة على شواطئ البحر الميت.',
        'desc' => 'يقدم فندق ماريوت تجربة استرخاء لا مثيل لها مع مسابح مياه مالحة، شاطئ خاص، ومركز صحي متكامل. يُعد الخيار الأمثل للعائلات والأزواج الباحثين عن الرفاهية.',
        'amenities' => [
            ['icon' => 'fa-water', 'name' => 'مسبح مياه مالحة'],
            ['icon' => 'fa-spa', 'name' => 'مركز صحي'],
            ['icon' => 'fa-umbrella-beach', 'name' => 'دخول مباشر للشاطئ'],
            ['icon' => 'fa-dumbbell', 'name' => 'نادي رياضي'],
        ],
        'phone' => '+962 5 356 0400',
        'whatsapp' => '962791112233',
        'status' => 'متاح للحجز',
    ],
    24 => [
        'id' => 24,
        'region' => 'deadsea',
        'name' => 'منتجع موفنبيك البحر الميت',
        'stars' => 5,
        'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        'price' => '175 دينار',
        'location' => 'سويمة، البحر الميت',
        'short_desc' => 'قرية عربية تقليدية فاخرة مع خدمات السبا العالمية.',
        'desc' => 'صُمم هذا المنتجع المذهل على طراز قرية عربية تقليدية بمباني حجرية وأزقة خلابة. يوفر وصولاً خاصاً للبحر الميت وعلاجات السبا المتنوعة.',
        'amenities' => [
            ['icon' => 'fa-monument', 'name' => 'تصميم قرية عربية'],
            ['icon' => 'fa-spa', 'name' => 'علاجات زارا سبا'],
            ['icon' => 'fa-umbrella-beach', 'name' => 'شاطئ خاص'],
            ['icon' => 'fa-child', 'name' => 'نادي أطفال'],
        ],
        'phone' => '+962 5 356 1111',
        'whatsapp' => '962799998888',
        'status' => 'متاح للحجز',
    ]
];
